### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by smartboyathome** [SuperTails/langcraft#2]
What is this licensed under? You should include the license in a LICENSE.txt file.

**Comment by SuperTails** [comment]
For consistency with most other Rust projects (and because I was comfortable with the terms) I went with the choice of either MIT or Apache-2.0 in e87f9db0ec3897eb12cc33282c3fc46bda6a3e94. I'm not 100% certain on how to deal with this sort of thing so if there's somewhere else I need to add a notice then do point it out.

**Comment by SuperTails** [comment]
I've asked around a bit and what I have now seems to be correct, so I'll consider this done.
